import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { getEntries } from "@/lib/contentstack";
import { normalizeNavigationEntries } from "@/lib/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 60;

function isInternalPath(href) {
  const h = String(href).trim();
  return h.startsWith("/") && !h.startsWith("//");
}

const navLinkClass =
  "text-sm font-medium text-zinc-700 transition hover:text-zinc-900 dark:text-zinc-300 dark:hover:text-zinc-100";

export default async function RootLayout({ children }) {
  let entries = [];
  try {
    entries = await getEntries("navigation_item");
  } catch {
    entries = [];
  }

  const items = normalizeNavigationEntries(entries);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-zinc-200 px-6 py-3 dark:border-zinc-800">
          <nav
            className="mx-auto flex max-w-6xl flex-wrap items-center gap-4"
            aria-label="Primary"
          >
            {items.map((item) =>
              isInternalPath(item.link) ? (
                <Link key={item.uid ?? item.link} href={item.link} className={navLinkClass}>
                  {item.label}
                </Link>
              ) : (
                <a
                  key={item.uid ?? item.link}
                  href={item.link}
                  className={navLinkClass}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {item.label}
                </a>
              ),
            )}
          </nav>
        </header>
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
